services:
  openresty:
    container_name: openresty
    build: .
    restart: always
    network_mode: host
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    mem_limit: 1g
    cpus: "2.0"
