error_page 400 401 403 404 405 406 407 408 409 410 418 429 451 500 501 502 503 504 /errors/error.html?code=$status;

location = /errors/error.html {
    alias /usr/local/openresty/nginx/errors/error.html;
    ssi on;
    internal;
}
